<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
	</array>
	<key>injections</key>
	<dict>
		<key>L:string.unquoted.heredoc.terraform - meta.embedded.line.terraform</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_terraform</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#resource</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#other_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#const</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#array</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hexadecimal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#heredoc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dict</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.terraform</string>
				</dict>
			</array>
		</dict>
		<key>assign_block</key>
		<dict>
			<key>begin</key>
			<string>^(?:\s*)([a-zA-Z0-9\_\-]+)\s*\=\s*(\{|\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.structure.identifier.terraform</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.keyword.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}|\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.block.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#const</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assign_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
			</array>
		</dict>
		<key>assignment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.key.terraform</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:\s*)([a-zA-Z0-9\_\-]+)\s*\=\s*</string>
			<key>name</key>
			<string>meta.structure.assignment.terraform</string>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>(?=^[ \t]+)?(\/\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*\/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.terraform</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=(#|\/\/))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.terraform</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.doubleslash.terraform</string>
				</dict>
			</array>
		</dict>
		<key>const</key>
		<dict>
			<key>match</key>
			<string>\b(false|true|any)\b</string>
			<key>name</key>
			<string>constant.language.boolean.terraform</string>
		</dict>
		<key>dict</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dict.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dict.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dict.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dict</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#const</string>
				</dict>
			</array>
		</dict>
		<key>function_call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-z0-9]+)[\W]*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>source.method.terraform</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.terraform</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.method-call.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#array</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function_call</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment_line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#const</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dict</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>"</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.terraform</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>double quoted strings, allows for interpolation</string>
							<key>end</key>
							<string>"</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.terraform</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.double.terraform</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolated_terraform</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.array.terraform</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>heredoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=(?&gt;&lt;&lt;("|'|)JSON\1$\n?))</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>name</key>
					<string>meta.embedded.block.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;&lt;)("|'|)(JSON)\2$\n?</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.terraform</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.json</string>
							<key>end</key>
							<string>^(\3)(?=\s|;|&amp;|$)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.unquoted.heredoc.terraform</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.json</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=(?&gt;&lt;&lt;("|'|)YAML\1$\n?))</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>name</key>
					<string>meta.embedded.block.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;&lt;)("|'|)(YAML)\2$\n?</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.terraform</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.yaml</string>
							<key>end</key>
							<string>^(\3)(?=\s|;|&amp;|$)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.unquoted.heredoc.terraform</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.yaml</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=(?&gt;&lt;&lt;("|'|)(SHELL|BASH|SH)\1$\n?))</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>name</key>
					<string>meta.embedded.block.shell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(&lt;&lt;)("|'|)(SHELL|BASH|SH)\2$\n?</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.begin.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.terraform</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.shell</string>
							<key>end</key>
							<string>^(\3)(?=\s|;|&amp;|$)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.string.end.terraform</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.heredoc-token.terraform</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.unquoted.heredoc.terraform</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.shell</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;&lt;)("|'|)(\w+)\2\n</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.terraform</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.heredoc.terraform</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(\3)(?=\s|;|&amp;|$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.terraform</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heredoc-token.terraform</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.unquoted.heredoc.terraform</string>
				</dict>
			</array>
		</dict>
		<key>hexadecimal</key>
		<dict>
			<key>comment</key>
			<string>handles hexadecimal numbers</string>
			<key>match</key>
			<string>\b0[xX]\h(?&gt;_?\h)*r?i?\b</string>
			<key>name</key>
			<string>constant.numeric.terraform</string>
		</dict>
		<key>interpolated_terraform</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$[\$]{0,1}\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.terraform</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.terraform.inline</string>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.terraform</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#reference</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function_call</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lookup</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.lookup.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.terraform</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>(?x:         # turn on extended mode
                  \b          # Be either the beginning of the line, require whitespace
			             -?         # an optional minus
			             (?:
			               0        # a zero
			               |        # ...or...
			               [1-9]    # a 1-9 character
			               \d*      # followed by zero or more digits
			             )
			             (?:
			               (?:
			                 \.     # a period
			                 \d+    # followed by one or more digits
			               )?
			             )?         # make decimal portion optional
                   (
                     [kKmMgG]b? # Do we have a trailing suffix?
                   )?         # 
                   \b
			           )</string>
			<key>name</key>
			<string>constant.numeric.terraform</string>
		</dict>
		<key>primitives</key>
		<dict>
			<key>match</key>
			<string>\b(string|number|bool)\b</string>
			<key>name</key>
			<string>constant.language.primitives.terraform</string>
		</dict>
		<key>reference</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>source.terraform.reference</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.terraform.reference</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.terraform.name</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.terraform.name</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.terraform.name</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.terraform.name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([a-z_0-9]+)\.([a-zA-Z\-_0-9]+)?(?:\.([a-zA-Z\-_0-9]+|\*))?(?:\.([a-zA-Z\-_0-9\*]+))?(?:\.([a-zA-Z\-_0-9]+))?</string>
					<key>name</key>
					<string>text.plain.terraform.reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lookup</string>
				</dict>
			</array>
		</dict>
		<key>resource</key>
		<dict>
			<key>begin</key>
			<string>^(?:\s*)([a-zA-Z0-9\_\-]+)(?:\s+("[a-zA-Z0-9\_\-]*"))?(?:\s+("[a-zA-Z0-9\_\-]*")?)?\s(\{)($)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.structure.identifier.terraform</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.resource.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.resource.type.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.resource.name.terraform</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.block.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.resource.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#const</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#resource</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assign_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ternary</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>double quoted strings, allows for interpolation</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_terraform</string>
				</dict>
			</array>
		</dict>
		<key>ternary</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.terraform</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.terraform</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\=\=)|(\?)|(\:)</string>
					<key>name</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>match</key>
			<string>\b(map|object|list|set|tuple)\b</string>
			<key>name</key>
			<string>constant.language.types.terraform</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>11E0E1FF-EF17-416F-BB21-7C568FB783BA</string>
</dict>
</plist>
