<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tfvars</string>
	</array>
	<key>name</key>
	<string>TFVars</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>(?=^[ \t]+)?(\/\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*\/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.terraform</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=(#|\/\/))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.terraform</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.terraform</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.doubleslash.terraform</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>double quoted strings, allows for interpolation</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tfvars</string>
	<key>uuid</key>
	<string>E9476B9C-8FDC-4FCA-9155-CE344CBA00BB</string>
</dict>
</plist>
