// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Terraform
{
    internal sealed partial class Vsix
    {
        public const string Id = "Terraform.d40d8829-581f-472c-aa5d-6514d5dbdde9";
        public const string Name = "Terraform";
        public const string Description = @"Basic language support for Terraform files (.tf and .tfvars) including syntax highlighting, comment/uncomment, brace completion, and more.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "terraform";
    }
}
